name: Validation

on:
  schedule:
    - cron: 30 0/4 * * *
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'wabbajack-tools/mod-lists'
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true        
    - name: Restore dependencies
      run: dotnet restore Validation/Validation.sln
    - name: Build
      run: dotnet build Validation/Validation.sln --no-restore 
    - name: Test
      run: dotnet test Validation/Validation.sln --no-build --verbosity normal
